spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ct?useSSL=false&serverTimezone=UTC
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 2
      connection-timeout: 500
      max-lifetime: 30000
      idle-timeout: 10000
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    local-cache-scope: STATEMENT
server:
  port: 8081

logging:
  level:
    com.example.demo: DEBUG
#    org.springframework.web: DEBUG
#    org.hibernate: INFO
#    org.mybatis: DEBUG
#    com.zaxxer.hikari: DEBUG
#    com.zaxxer.hikari.HikariConfig: DEBUG
#    com.zaxxer.hikari.pool: TRACE

